name: VoxAi
description: A voice-powered AI assistant built with Jaspr, providing intuitive speech recognition and natural language processing for seamless voice interactions across web platforms.
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  jaspr: ^0.18.0
  jaspr_flutter_embed: ^0.4.5
  jaspr_riverpod: ^0.3.19
  jaspr_router: ^0.6.4
  jaspr_tailwind: ^0.3.3
  markdown: ^7.3.0
  text_to_speech: ^0.2.3


dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  jaspr_builder: ^0.18.0
  jaspr_lints: ^0.3.1
  jaspr_web_compilers: ^4.1.1

jaspr:
  mode: client

flutter:
  uses-material-design: true
